version: '3'

services:
  forwarder:
    image: splunk/universalforwarder:latest
    environment:
    - 'SPLUNK_PASSWORD=changeme'
    - 'SPLUNK_START_ARGS=--accept-license'
    ports:
    - '9997:9997'
  server:
    image: splunk/splunk:latest
    ports:
    - '8001:8000'
    environment:
    - 'SPLUNK_PASSWORD=changeme'
    - 'SPLUNK_START_ARGS=--accept-license'

