version: '3'

services:
  forwarder:
    image: splunk/universalforwarder:latest
    environment:
    - 'SPLUNK_PASSWORD=changeme'
    - 'SPLUNK_START_ARGS=--accept-license'
    ports:
    - '9997:9997'
    volumes:
    - ./appdata:/appdata

  server:
    image: splunk/splunk:latest
    ports:
    - '8001:8000'
    environment:
    - 'SPLUNK_PASSWORD=changeme'
    - 'SPLUNK_START_ARGS=--accept-license'

  app:
    build: ./fake_container
    environment:
    - 'DESTINATION_FILE=/appdata/test.log'
    command: 'bash -c "/app/generate_fake.sh"'
    volumes:
    - ./appdata:/appdata
